Documentation Sync with Discourse
canonical/postgresql-k8s-operator pull request #120
Opened 2023-03-29 17:43 UTC by deusebio

2023-03-30 21:28 UTC, taurus-forever commented
@deusebio any ideas why charmcraft build is not happy here (trying yo copy tutorial?).

2023-03-30 21:34 UTC, dragomirp commented
> @deusebio any ideas why `charmcraft pack` is not happy here (trying yo copy tutorial?).

Sometimes caches are assigned to the wrong branch which breaks the packing. IIRC it's a github bug. It should build fine now.

2023-03-31 11:40 UTC, taurus-forever approved these changes

2023-03-31 12:19 UTC, marceloneppel requested changes

2023-04-03 11:24 UTC, dragomirp commented
> @dragomirp Do you have any examples of this happening? I'd like to confirm it's a GitHub bug and not an issue with the workflow

Not currently, but if I see it happen again I'll ping you.

2023-04-03 16:39 UTC, marceloneppel approved these changes

2023-04-03 18:35 UTC, merged