Separate s3 relations
canonical/postgresql-k8s-operator pull request #143
Opened 2023-04-17 20:43 UTC by marceloneppel

## Issue
Jira tickets: [DPE-1665](https://warthogs.atlassian.net/browse/DPE-1665) and partially [DPE-556](https://warthogs.atlassian.net/browse/DPE-556)

To avoid messing up with backups from another cluster repository it's needed to have separate relations for backup and restore.

## Solution
This PR also fixes in this charm the issues reported for the VM charm on [DPE-1624](https://warthogs.atlassian.net/browse/DPE-1624), [DPE-1625](https://warthogs.atlassian.net/browse/DPE-1625) and [DPE-1584](https://warthogs.atlassian.net/browse/DPE-1584).

Create separate relations for backup and restore (use repo=2 to the restore relation).

Alerted the user with a blocked status if trying to configure backups to a S3 path where there are already backups from another cluster.

Unblock the charm when new S3 settings are informed (and are valid).

Added `/` to the beginning of the S3 path when it's not configured with that in the S3 integrator.

[DPE-1665]: https://warthogs.atlassian.net/browse/DPE-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-556]: https://warthogs.atlassian.net/browse/DPE-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1624]: https://warthogs.atlassian.net/browse/DPE-1624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1625]: https://warthogs.atlassian.net/browse/DPE-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1584]: https://warthogs.atlassian.net/browse/DPE-1584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-20 06:51 UTC, delgod requested changes

2023-04-20 06:51 UTC, delgod commented on src/charm.py
>              stanza=self.app_peer_data.get("stanza"),
on restore we put an empty string `""` into relation, what value do we get here? empty string or None?
the problem here, is that in `render_patroni_yml_file`, depending on the value we enable pgbackrest as an archive command if `enable_pgbackrest=stanza is not None`.
but in python empty string is not None

2023-04-20 11:00 UTC, taurus-forever reviewed
1) I am fine with new approach
2) I am feeling uncomfortable due to different relation names for all other charms. We have been blamed already for the lack of consistency.
3) isn't s3-integrator "endpoints" are way to separate backup and restore credential / buckets? In this case the same interface can be used publicly, but internally you can differentiate them using different endpoints.

BTW, what is the use-case to restore the same cluster?
1) juju relate postgresql-k8s:backup-s3-relations s3-interface
2) juju run-action postgresql-k8s create-backup ...
3) juju remove-relation postgresql-k8s:backup-s3-relations s3-interface
4) juju relate postgresql-k8s:restore-s3-relations s3-interface
5) juju run-action postgresql-k8s/leader restore backup-id=YYYY-MM-DDTHH:MM:SSZ ...

Ufff....

2023-04-28 15:29 UTC, marceloneppel commented
Superseded by https://github.com/canonical/postgresql-k8s-operator/pull/147 after the discussion with Mohamed.

2023-04-28 15:29 UTC, closed without merging