[DPE-1769] Minor version upgrades
canonical/postgresql-k8s-operator pull request #199
Opened 2023-07-12 20:30 UTC by marceloneppel

## Issue

## Solution

2023-07-27 06:16 UTC, delgod requested changes

2023-07-27 11:45 UTC, marceloneppel commented on requirements.txt
> -anyio==3.7.1 ; python_full_version >= "3.10.6" and python_full_version < "4.0.0" \
Yes, we can. But we disabled it temporarily due to https://github.com/canonical/charmcraft/issues/1179. I forgot to add it to this PR description. I added it now. We used `poetry export --without-hashes -f requirements.txt -o requirements.txt` to make the charm build until the issue in charmcraft is resolved.

2023-07-27 11:45 UTC, marceloneppel commented on src/upgrade.py
> +        if not self.charm._patroni.member_started:
I think it's possible. I'm gonna implement it today.

2023-07-27 11:47 UTC, marceloneppel commented on src/dependency.json
> +{
I'm not sure if it's possible or not. Let me check and test it.

2023-07-28 21:59 UTC, marceloneppel commented on src/dependency.json
> +{
It's possible. I specified the rock PG version in https://github.com/canonical/postgresql-k8s-operator/pull/199/commits/1f246e2f360067876632c223223c3806a95d3582.

2023-07-28 21:59 UTC, marceloneppel commented on src/upgrade.py
> +        if not self.charm._patroni.member_started:
Added on https://github.com/canonical/postgresql-k8s-operator/pull/199/commits/1f246e2f360067876632c223223c3806a95d3582.

2023-08-01 06:26 UTC, delgod approved these changes

2023-08-03 13:31 UTC, dragomirp approved these changes

2023-08-07 23:17 UTC, merged