update docs
canonical/postgresql-k8s-operator pull request #61
Opened 2022-11-15 09:47 UTC by beliaev-maksim

* limit README.md line length to 99 chars
* add docs on relation and links to data libs

2022-11-15 11:40 UTC, beliaev-maksim commented
I am 99.99% percent sure that integration fails **not** because of the markdown change :)

2022-11-15 19:07 UTC, marceloneppel requested changes
It seems that something failed in the process of packing the charm (but it succeeded in the other tests and in a later attempt), but I couldn't find any logs on the action run that should help us understand what happened.

2022-11-15 19:07 UTC, marceloneppel commented on README.md
> +juju integrtate postgresql-k8s application
```suggestion
juju integrate postgresql-k8s application
```

2022-11-16 19:53 UTC, marceloneppel approved these changes

2022-11-17 10:37 UTC, dragomirp approved these changes

2022-11-17 10:50 UTC, marceloneppel commented
Thanks for the contribution Maksim!

2022-11-17 10:50 UTC, beliaev-maksim commented
@dragomirp @marceloneppel 
can you merge then pls ?

2022-11-17 10:50 UTC, merged